[green_agent]
name = "codewalk-eval-agent"
#agentbeats_id = "019bc4f3-9e0f-7ba3-8fee-9291241a4d98"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }
image = "codewalk-eval-agent:latest"

[[participants]]
name = "codewalk-qa-agent"
#agentbeats_id = "019c025e-dd8c-7360-a0e4-3606f0571a4d"
image = "codewalk-qa-agent:latest"
env = { QA_API_KEY = "${GOOGLE_API_KEY}", QA_DATA_DIR = "data", QA_MODEL = "gemini-2.5-flash" }

[config]
question = "How does request processing work in FastAPI?"
repo_url = "https://github.com/tiangolo/fastapi"
judge_model = "gemini-2.5-flash"
